# Generated by Django 4.2.8 on 2023-12-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentapp', '0003_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='submitted_by',
        ),
    ]
