# Generated by Django 4.2.8 on 2023-12-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentapp', '0004_remove_assignment_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.CharField(default='9999999999', max_length=10),
        ),
    ]
