# Generated by Django 4.2.8 on 2023-12-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentapp', '0010_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='message',
        ),
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
