# Generated by Django 4.2.8 on 2023-12-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentapp', '0020_alter_assignment_uploadeddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('Checked', 'Checked'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
