# Generated by Django 4.2.8 on 2023-12-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentapp', '0021_assignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('Checked', 'Checked'), ('Submitted', 'Submitted')], default='Submitted', max_length=10),
        ),
    ]
