# Generated by Django 4.2.8 on 2023-12-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentapp', '0023_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='remarks',
            field=models.TextField(default='No Remarks'),
        ),
    ]
