# Generated by Django 4.2.8 on 2023-12-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentapp', '0024_assignment_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isteacher',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
